export const CHINA_REGION = [
  {
    ename: 'Anhui',
    code: 340000,
  },
  {
    ename: 'Beijing',
    code: 110000,
  },
  {
    ename: 'Chongqing',
    code: 500000,
  },
  {
    ename: 'Fujian',
    code: 350000,
  },
  {
    ename: 'Gansu',
    code: 620000,
  },
  {
    ename: 'Guangdong',
    code: 440000,
  },
  {
    ename: 'Guangxi',
    code: 450000,
  },
  {
    ename: 'Guizhou',
    code: 520000,
  },
  {
    ename: 'Hainan',
    code: 460000,
  },
  {
    ename: 'Hebei',
    code: 130000,
  },
  {
    ename: 'Heilongjiang',
    code: 230000,
  },
  {
    ename: 'Henan',
    code: 410000,
  },
  {
    ename: 'Hubei',
    code: 420000,
  },
  {
    ename: 'Hunan',
    code: 430000,
  },
  {
    ename: 'Inner Mongolia Autonomous Region',
    code: 150000,
  },
  {
    ename: 'Jiangsu',
    code: 320000,
  },
  {
    ename: 'Jiangxi',
    code: 360000,
  },
  {
    ename: 'Jilin',
    code: 220000,
  },
  {
    ename: 'Liaoning',
    code: 210000,
  },
  {
    ename: 'Ningxia Hui Autonomous Region',
    code: 640000,
  },
  {
    ename: 'Qinghai',
    code: 630000,
  },
  {
    ename: 'Shaanxi',
    code: 610000,
  },
  {
    ename: 'Shandong',
    code: 370000,
  },
  {
    ename: 'Shanghai',
    code: 310000,
  },
  {
    ename: 'Shanxi',
    code: 140000,
  },
  {
    ename: 'Sichuan',
    code: 510000,
  },
  {
    ename: 'Tianjin',
    code: 120000,
  },
  {
    ename: 'Tibet',
    code: 540000,
  },
  {
    ename: 'Xinjiang Uyghur Autonomous Region',
    code: 650000,
  },
  {
    ename: 'Yunnan',
    code: 530000,
  },
  {
    ename: 'Zhejiang',
    code: 330000,
  },
  {
    ename: 'Taiwan',
    code: 710000,
  },
  {
    ename: 'Hong Kong',
    code: 810000,
  },
  {
    ename: 'Macao',
    code: 820000,
  },
];

export const LabelsData = [
  {
    name: '',
    position: ['113.280637', '23.125178'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '广东',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['113.665412', '34.757975'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '河南',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['111.670801', '40.818311'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '内蒙古',
      direction: 'top',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['126.642464', '45.756967'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '黑龙江',
      direction: 'top',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['87.617733', '43.792818'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '新疆',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['114.298572', '30.584355'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '湖北',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['123.429096', '41.796767'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '辽宁',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['117.000923', '36.675807'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '山东',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['108.948024', '34.263161'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '陕西',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['121.472644', '31.231706'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '上海',
      direction: 'right',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['106.713478', '26.578343'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '贵州',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['106.504962', '29.533155'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '重庆',
      direction: 'right',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['91.132212', '29.660361'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '西藏',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['117.283042', '31.86119'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '安徽',
      direction: 'top',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['119.306239', '26.075302'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '福建',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['112.982279', '28.19409'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '湖南',
      direction: 'left',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['110.33119', '20.031971'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '海南',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['118.767413', '32.041544'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '江苏',
      direction: 'right',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['101.778916', '36.623178'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '青海',
      direction: 'left',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['108.320004', '22.82402'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '广西',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['106.278179', '38.46637'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '宁夏',
      direction: 'bottom',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['115.892151', '28.676493'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '江西',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['120.153576', '30.287459'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '浙江',
      direction: 'bottom',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['114.502461', '38.045474'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '河北',
      direction: 'right',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['113.54909', '22.198951'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '澳门',
      direction: 'bottom',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['121.509062', '25.044332'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '台湾',
      direction: 'bottom',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['114.173355', '22.320048'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '香港',
      direction: 'right',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['103.823557', '36.058039'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '甘肃',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['104.065735', '30.659462'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '四川',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['125.3245', '43.886841'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '吉林',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['117.190182', '39.125596'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '天津',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['102.712251', '25.040609'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '云南',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['116.405285', '39.904989'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '北京',
      direction: 'top',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
  {
    name: '',
    position: ['112.549248', '37.857014'],
    zooms: [4, 13],
    zIndex: 1,
    opacity: 1,
    text: {
      content: '山西',
      direction: 'center',
      offset: [0, 0],
      zooms: [3, 20],
      style: {
        fontSize: 10,
        fontWeight: 'normal',
        fillColor: '#eee',
        strokeColor: '#88f',
        strokeWidth: 2,
      },
    },
  },
];
